// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eticaret.Data.Concrete;

#nullable disable

namespace eticaret.Web.Migrations
{
    [DbContext(typeof(eticaretDbContext))]
    [Migration("20240509180031_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eticaret.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "iyi tel",
                            Name = "samsung s24",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "iyi tel",
                            Name = "samsung s23",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "iyi tel",
                            Name = "samsung s22",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "iyi tel",
                            Name = "samsung s21",
                            Price = 40000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
